### ISSUE TITLE
Docs should explain difference between `#:definitions` and `#:editor`

### ISSUE THREAD

**Issue by AlexKnauth** [david-christiansen/todo-list#3]
What's the intended difference between `#:definitions` and `#:editor`?

The definitions-text objects in DrRacket are editors, and the code of this todo-list tool seems to pass the same object to both arguments.

Is there supposed to be a difference between them? Are there properties or methods that we shouldn't rely on for one but can for the other?

**Comment by david-christiansen** [comment]
I would eventually like to support editing commands in the interactions pane as well, and those interactions should be able to ask for the definitions window to get information about the program being developed. This isn't supported yet, though.

**Comment by david-christiansen** [comment]
That is, use `#:editor` when you want the place where the code is being edited.

**Comment by AlexKnauth** [comment]
Okay. So if something could be in the interactions window, you would use `#:editor` for (the editor where the code is being edited) and `#:definitions` for (other stuff that might be important for context). Thanks!

Should the docs mention this distinction?

**Comment by david-christiansen** [comment]
Indeed they should!

**Comment by AlexKnauth** [comment]
Thank you!
