### ISSUE TITLE
Associating a goal with a different expression

### ISSUE THREAD

**Issue by AlexKnauth** [david-christiansen/todo-list#5]
Is there a way, or should there be a way, of associating a goal with a different expression? In my case I want to associate it with a "parent" expression.

Specificly, I have a bunch of definitions using `my-define`. `(my-define x e)` defines `x` as the value of `e`, but it also adds some compile-time information for other macros to use. This compile-time information does *not* depend on expanding `e`.

I want each of these to have a goal associated with it, but I want each goal to depend on the compile-time information from other `my-define` definitions, even the ones below it in the file.

This is fine as long as I only attach the syntax property when the `e` is expanded. However, then only the `e` is associated with the goal, not the `(my-define x e)`.

Is there a way (or if not, should there be a way) to attach a goal syntax property to one expression, but have it associated with a different expression?

**Comment by AlexKnauth** [comment]
Currently, my workaround is having my-define's body expand to `(begin '(my-define x e) e)`, where the my-define expression in the quote has the syntax property.

**Comment by david-christiansen** [comment]
That's a good question.

One way to do this would be to adopt a protocol similar to the tooltips in DrRacket - the syntax property would point at a cons tree of vectors that describe source locations and goals. This would also allow a single goal to involve multiple source locations, and it would allow a logger protocol to be used for files that don't macroexpand properly.  This comes at a cost of simplicity, however, and additionally makes the fact that syntax objects and DrRacket have different ideas of what positions are.

Perhaps goals could be made into prefab structs that contain a `source-location?`, a detailed description, and an optional summary. Then, the syntax property would have a cons tree of these, making it easier for non-local information to be used.

Would this solve your use case?

**Comment by AlexKnauth** [comment]
Yes.

**Comment by AlexKnauth** [comment]
What about editing-commands? Should macros be able to associate them with different expressions in the same way as goals?

**Comment by david-christiansen** [comment]
That seems reasonable enough.

What are you building with this?

**Comment by AlexKnauth** [comment]
This is an example of how it works when the editing-command only relies on itself and the stuff before it. In other examples the editing-command should be able to rely on the stuff after it too, because of the `(my-define x e)` -> `(define x (begin '(my-define x e) e))` hack. I want to get rid of that hack and replace it with a version of your "prefab struct that contains a source-location" solution, but for editing commands.

<img width="1072" alt="screenshot-1" src="https://user-images.githubusercontent.com/6600123/33088841-d8753c10-cebc-11e7-9291-ce18ed417ae7.png">

<img width="961" alt="screenshot-2" src="https://user-images.githubusercontent.com/6600123/33088830-cd6286c0-cebc-11e7-8655-10ba26b4b38b.png">
<img width="1072" alt="screenshot-3" src="https://user-images.githubusercontent.com/6600123/33088833-cf69f070-cebc-11e7-8b17-10f777f2812c.png">
